;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-save-default nil)
 '(command-log-mode-window-size 50)
 '(company-dabbrev-minimum-length 3)
 '(company-dabbrev-other-buffers nil)
 '(company-show-numbers t)
 '(company-statistics-auto-restore nil)
 '(company-tabnine-max-num-results 9)
 '(compilation-message-face 'default)
 '(ctags-update-delay-seconds 1024)
 '(cua-global-mark-cursor-color "#2aa198")
 '(cua-normal-cursor-color "#839496")
 '(cua-overwrite-cursor-color "#b58900")
 '(cua-read-only-cursor-color "#859900")
 '(custom-safe-themes
   '("1d50bd38eed63d8de5fcfce37c4bb2f660a02d3dff9cbfd807a309db671ff1af" "99ea831ca79a916f1bd789de366b639d09811501e8c092c85b2cb7d697777f93" "e1ecb0536abec692b5a5e845067d75273fe36f24d01210bf0aa5842f2a7e029f" "1526aeed166165811eefd9a6f9176061ec3d121ba39500af2048073bea80911e" "76bfa9318742342233d8b0b42e824130b3a50dcc732866ff8e47366aed69de11" default))
 '(eaf-find-alternate-file-in-dired t)
 '(eaf-python-command "/usr/bin/python3")
 '(elfeed-feeds
   '("https://manateelazycat.github.io/feed.xml"
     ("https://rss.lilydjwg.me/zhihuzhuanlan/abtesting")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/cldpml")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/gashero")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/dteratech")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/DCF-tracking")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/DL4NLP")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/codesign")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/aixueren")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/shanren7")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_29122335")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/brand")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/taosay")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_80412427")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/ai4application")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/AIdesign")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_123261973")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/intelligentunit")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/algorithmicliberalartsdegree")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/tianshansoft")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/pythoncoder")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/sharerl")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/panyiming")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/xTechDay")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/robotang")
     ("https://rss.lilydjwg.me/zhihu/xin-zhi-yuan-88-3")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/washu")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/-anki")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/lmrebuilt")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/chenshuo")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/silicontrader")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/growingio")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/HicRhodushicsalta")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/Windrivder")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/burness-DL")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/operations-research")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/jiqizhixin")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/data-analyst-improvement")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/jiqizhineng")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/yufree")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/dreawer")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/nlp-izakaya")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/qianxiaosi")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/RucAIBox")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/reinforce")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/xitucheng10")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/googledevelopers")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/brainimaging")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/passer")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/data-analysis")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/litaoye")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/ml-etali")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/linuxcn")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_94953554")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/jeldor-latex")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_32667517")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/largescale-ml")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/binlearning-dl")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/cvprnet")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/loan-analytics")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/nullptr")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/python-cn")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/data-mining")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/prml-paper-reading")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/mlearn")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/mittechreview")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/cold-code")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_126470847")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/cyh24")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/notes-of-algorithm")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/chenran")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/hellobi")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/Charles-Wang")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/evanyou")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/auxten")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/deeplearning-surfing")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/PhantomY")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/feizong")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/learningneuroscience")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/visual-tracking")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/TensorFlownews")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/dlclass")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/bigdata")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/pixelife")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/notageek")
     ("https://raw.githubusercontent.com/RickyWong33/Machine_Learning_RSS/master/zhihu/collection/AI/113183484.xml")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/xiaoleimlnote")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_33365682")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/beimingyouyu")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/smartman163")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/zkyzs")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/computercoil")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/naodongjulebu")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/simons")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/gpml2016")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/qinlibo-ml")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/sss95zz")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/visualthinking")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/lunwen")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/milocode")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/ai-leader")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/henuwangkai")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/machine-learning-book")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/it-comment-from-a-fool")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/shiyanlou")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/sangwf")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/textmining-experience")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/TsingJyuData")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/one-paper-a-week")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/hacker-and-painter")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/Stark")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/onionbots")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/xiaoxueli")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/slackers")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/g1n0st")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/pythoneer")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_70349842")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/NLPBlog-WuYu")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/openai")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/codelover")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/neureality")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/netjob")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/bigquant")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/resyschina")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/startdl")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/nihaoCPP")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/lurenjia")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/qiuneitui")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/jnshu")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/dlalchemy")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/designintelligence")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/ai-insight")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/YJango")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_76512067")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_84661256")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/learn-robotics")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_120224762")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/coders")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/ItsFuture")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/databaseoncloud")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/rendering-fantasy")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/psy-os")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/distributed")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/geekonomics10000")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/zhoubo")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/furthersight")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/rocks")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/theoretical-machine-learning")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/datanalysis")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_73407294")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/easyml")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/xmucpp")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/aresmiki")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/aiandlaw")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/hsmyy")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/quantumliu")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/c_125238795")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/AlfredWorkflow")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/starkwang")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/daniujiangtang")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/mBrain")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/gomxnet")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/mathNote")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/robotdrkong")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/gongwenjia")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/dlcode")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/paperweekly")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/mathincg")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/marisa")
     ("https://rsshub.app/kaggle/competitions")
     ("https://rsshub.app/github/trending/daily")
     ("https://rsshub.app/zhihu/daily/section/2")
     ("https://manateelazycat.github.io/feed.xml")
     ("https://rss.lilydjwg.me/zhihuzhuanlan/dxww")
     ("https://rsshub.app/blogs/wangyin")))
 '(erc-nick "liuyan")
 '(erc-port 6666)
 '(evil-want-C-i-jump t)
 '(evil-want-Y-yank-to-eol nil)
 '(exec-path-from-shell-arguments '("-l"))
 '(expand-region-contract-fast-key "V")
 '(expand-region-exclude-text-mode-expansions '(html-mode nxml-mode web-mode))
 '(expand-region-reset-fast-key "r")
 '(flycheck-python-flake8-executable "/home/liuyan/.conda/envs/torch/bin/python")
 '(global-command-log-mode nil)
 '(helm-buffer-max-length 56)
 '(helm-move-to-line-cycle-in-source t)
 '(highlight-changes-colors '("#d33682" "#6c71c4"))
 '(highlight-indent-guides-auto-character-face-perc 7)
 '(highlight-indent-guides-delay 0)
 '(highlight-indent-guides-method 'character)
 '(highlight-indent-guides-responsive 'top)
 '(highlight-symbol-colors
   '("#3b6b40f432d6" "#07b9463c4d36" "#47a3341e358a" "#1d873c3f56d5" "#2d86441c3361" "#43b7362d3199" "#061d417f59d7"))
 '(highlight-symbol-foreground-color "#93a1a1")
 '(highlight-tail-colors
   '(("#073642" . 0)
     ("#5b7300" . 20)
     ("#007d76" . 30)
     ("#0061a8" . 50)
     ("#866300" . 60)
     ("#992700" . 70)
     ("#a00559" . 85)
     ("#073642" . 100)))
 '(hl-bg-colors
   '("#866300" "#992700" "#a7020a" "#a00559" "#243e9b" "#0061a8" "#007d76" "#5b7300"))
 '(hl-fg-colors
   '("#002b36" "#002b36" "#002b36" "#002b36" "#002b36" "#002b36" "#002b36" "#002b36"))
 '(hl-todo-keyword-faces
   '(("TODO" . "#dc752f")
     ("NEXT" . "#dc752f")
     ("THEM" . "#2d9574")
     ("PROG" . "#4f97d7")
     ("OKAY" . "#4f97d7")
     ("DONT" . "#f2241f")
     ("FAIL" . "#f2241f")
     ("DONE" . "#86dc2f")
     ("NOTE" . "#b1951d")
     ("KLUDGE" . "#b1951d")
     ("HACK" . "#b1951d")
     ("TEMP" . "#b1951d")
     ("FIXME" . "#dc752f")
     ("XXX+" . "#dc752f")
     ("\\?\\?\\?+" . "#dc752f")))
 '(ivy-height 18)
 '(lsp-flycheck-live-reporting nil)
 '(lsp-ui-doc-border "#93a1a1")
 '(lsp-ui-flycheck-live-reporting nil)
 '(lua-documentation-url "http://www.lua.org/manual/5.3/manual.html")
 '(magit-use-overlays nil)
 '(make-backup-files nil)
 '(nrepl-message-colors
   '("#dc322f" "#cb4b16" "#b58900" "#5b7300" "#b3c34d" "#0061a8" "#2aa198" "#d33682" "#6c71c4"))
 '(only-global-abbrevs t)
 '(org-agenda-custom-commands nil)
 '(org-agenda-ndays 1)
 '(org-agenda-show-all-dates t)
 '(org-agenda-skip-deadline-if-done t)
 '(org-agenda-skip-deadline-prewarning-if-scheduled t)
 '(org-agenda-skip-scheduled-if-done t)
 '(org-agenda-start-on-weekday nil)
 '(org-agenda-text-search-extra-files '(agenda-archives))
 '(org-deadline-warning-days 14)
 '(org-fast-tag-selection-single-key 'expert)
 '(org-log-into-drawer t)
 '(org-pomodoro-play-sounds nil)
 '(org-reverse-note-order t)
 '(org-roam-buffer-position 'left)
 '(org-roam-buffer-width 0.2)
 '(org-roam-completion-system 'ivy)
 '(org-roam-directory "~/org-notes/notes")
 '(org-roam-link-title-format "R:%s")
 '(package-selected-packages
   '(bm awesome-tab langtool helm-posframe function-args mw-thesaurus lpy jeison evil-snipe doom-themes color-rg meow bbyac browse-kill-ring delete-block grep-dired thing-edit ebib org-ref key-chord helm-bibtex figlet org-noter ivy-bibtex biblio parsebib biblio-core elfeed-org elfeed-goodies noflet ivy-posframe webkit-katex-render try rime posframe insert-translated-name ob-ipython speed-type ein polymode anaphora websocket highlight-indent-guides super-save company-english-helper pandoc-mode ox-pandoc wakatime-mode xkcd helpful elisp-refs loop zetteldeft flyspell-popup git-gutter-fringe git-gutter benchmark-init pdf-tools grip-mode vmd-mode org-preview-html company-tabnine utop tuareg caml seeing-is-believing ruby-refactor ruby-hash-syntax rubocopfmt ocp-indent ob-elixir mvn meghanada maven-test-mode lsp-java groovy-mode groovy-imports gradle-mode flycheck-ocaml merlin flycheck-mix flycheck-credo dune alchemist elixir-mode zeal-at-point insert-shebang flycheck-bashate fish-mode fasd counsel-dash dash-docs company-shell treemacs-persp magit-section pyim-basedict xr terminal-here flycheck-elsa leetcode aio ycmd request-deferred treemacs-magit vterm attrap hybrid-mode lispyville anki-editor pyim pangu-spacing find-by-pinyin-dired chinese-wbim chinese-conv ace-pinyin pinyinlib python unicode-escape plantuml-mode dap-mode bui tree-mode lsp-ui lsp-treemacs lsp-python-ms helm-lsp cquery company-lsp ccls forge closql emacsql-sqlite emacsql cpp-auto-include company-reftex parseedn lv parseclj a ox-hugo emojify emoji-cheat-sheet-plus company-emoji ob-typescript deadgrep org-cliplink devdocs ssh-agency org-projectile org-category-capture treemacs-projectile treemacs-evil treemacs pfuture transient osx-clipboard lsp-haskell lsp-mode flycheck-package package-lint evil-textobj-line blacken dante lcr company-ghc ghc helm-hoogle intero hlint-refactor hindent haskell-snippets flycheck-haskell company-ghci haskell-mode company-cabal cmm-mode imenu-list writeroom-mode visual-fill-column symbol-overlay treepy graphql sound-wav caps-lock doom-modeline eldoc-eval shrink-path ivy-rich prettier-js ivy-yasnippet gitignore-templates evil-goggles sesman dotenv-mode rjsx-mode magit-svn json-navigator hierarchy yasnippet-snippets spaceline-all-the-icons all-the-icons memoize pippel pipenv overseer org-mime nameless ivy-xref ivy-rtags importmagic epc concurrent google-c-style flycheck-rtags evil-cleverparens counsel-gtags counsel-css company-rtags rtags clojure-cheatsheet centered-cursor-mode font-lock+ ghub let-alist seq restclient-helm org-brain sayid evil-lion auctex-latexmk auctex password-generator realgud test-simple loc-changes load-relative company-lua blog-admin string-inflection opencl-mode cuda-mode symon rspec-mode fuzzy browse-at-remote winum helm-swoop unfill highlight-global marshal ht ob-restclient company-restclient know-your-http-well counsel-projectile lispy counsel swiper ivy-purpose hide-comnt helm-purpose window-purpose zoutline minitest glsl-mode pug-mode magithub editorconfig dockerfile-mode docker tablist docker-tramp helm-projectile xterm-color shell-pop eshell-z eshell-prompt-extras esh-help graphviz-dot-mode py-isort dumb-jump restclient racket-mode faceup projectile-rails ob-http helm-gtags feature-mode company-auctex rvm ruby-tools ruby-test-mode rubocop robe rbenv rake enh-ruby-mode chruby bundler inf-ruby yapfify sicp helm-mode-manager org origami tiny evil-unimpaired helm-pydoc unicode-whitespace github-search flycheck-clojure evil-escape mwim helm-github-stars fcitx solarized-theme tide typescript-mode spaceline powerline org-plus-contrib ivy-hydra helm-gitignore helm-flx helm-descbinds helm-css-scss helm-company helm-ag helm helm-core flyspell-correct-ivy color-identifiers-mode ag bracketed-paste paradox inflections cider names yaml-mode which-key wgrep uuidgen toc-org smex smeargle smartparens reveal-in-osx-finder restart-emacs ranger pytest py-yapf prodigy persp-mode pcre2el osx-trash org-pomodoro mmm-mode markdown-mode lua-mode live-py-mode link-hint launchctl js2-mode jade-mode info+ ibuffer-projectile projectile hy-mode htmlize hl-todo help-fns+ haml-mode gnuplot gitignore-mode github-clone popup git-gutter-fringe+ git-gutter+ flyspell-correct flycheck evil-visual-mark-mode evil-magit magit-popup git-commit with-editor evil-indent-plus iedit evil-ediff evil undo-tree diminish diff-hl ivy tern company column-enforce-mode cmake-mode clojure-snippets eval-sexp-fu pkg-info clojure-mode bind-map bind-key yasnippet auto-compile packed anaconda-mode pythonic ace-window ace-link avy quelpa package-build wrap-region visual-regexp-steroids visual-regexp peep-dired osx-dictionary nodejs-repl litable keyfreq gulpjs find-file-in-project etags-select ctags-update beacon 4clojure moe-theme edn paredit queue peg json-rpc dash-functional web-completion-data makey anzu highlight goto-chg flx gh logito pcache pos-tip guide-key request parent-mode simple-httpd json-snatcher json-reformat multiple-cursors moz ctable orglue epic alert log4e gntp spinner epl hydra async deferred f s chinese-word-at-point dash youdao-dictionary ws-butler web-mode web-beautify volatile-highlights vi-tilde-fringe use-package tagedit smooth-scrolling slim-mode scss-mode sass-mode rfringe reveal-in-finder rainbow-mode rainbow-identifiers rainbow-delimiters pyvenv pyenv-mode popwin pip-requirements persp-projectile pbcopy page-break-lines ox-reveal org-repo-todo org-present org-octopress org-mac-link org-download org-bullets open-junk-file neotree multi-term moz-controller move-text monokai-theme markdown-toc magit macrostep linum-relative leuven-theme less-css-mode json-mode js2-refactor js-doc indent-guide impatient-mode ido-vertical-mode hungry-delete hl-anything highlight-parentheses highlight-numbers highlight-indentation guide-key-tip google-translate golden-ratio github-browse-file gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link gist gh-md ggtags geiser fringe-helper flycheck-ycmd flycheck-pos-tip flx-ido fill-column-indicator fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-tutor evil-terminal-cursor-changer evil-surround evil-search-highlight-persist evil-org evil-numbers evil-nerd-commenter evil-matchit evil-lisp-state evil-jumper evil-indent-textobject evil-iedit-state evil-exchange evil-args evil-anzu engine-mode emmet-mode elisp-slime-nav elfeed discover-my-major deft dash-at-point cython-mode company-ycmd company-web company-tern company-statistics company-quickhelp company-c-headers company-anaconda command-log-mode coffee-mode cmake-font-lock clj-refactor clean-aindent-mode clang-format cider-eval-sexp-fu chinese-fonts-setup buffer-move auto-yasnippet auto-highlight-symbol auto-dictionary align-cljlet aggressive-indent adaptive-wrap ace-jump-mode ac-ispell 2048-game))
 '(paradox-github-token t)
 '(pdf-view-midnight-colors '("#b2b2b2" . "#292b2e"))
 '(pos-tip-background-color "#073642")
 '(pos-tip-foreground-color "#93a1a1")
 '(ring-bell-function 'ignore)
 '(safe-local-variable-values
   '((git-commit-major-mode . git-commit-elisp-text-mode)
     (typescript-backend . tide)
     (javascript-backend . tern)
     (eval progn
           (pp-buffer)
           (indent-buffer))
     (typescript-backend . lsp)
     (javascript-backend . lsp)
     (eval setenv "PYTHONPATH" "/home/liuyan/.conda/envs/torch/bin")))
 '(smartrep-mode-line-active-bg (solarized-color-blend "#859900" "#073642" 0.2))
 '(sp-show-pair-from-inside t)
 '(super-save-auto-save-when-idle t)
 '(tags-revert-without-query t)
 '(term-default-bg-color "#002b36")
 '(term-default-fg-color "#839496")
 '(vc-annotate-background-mode nil)
 '(vc-follow-symlinks t)
 '(wakatime-python-bin nil)
 '(web-mode-markup-indent-offset 2)
 '(weechat-color-list
   '(unspecified "#002b36" "#073642" "#a7020a" "#dc322f" "#5b7300" "#859900" "#866300" "#b58900" "#0061a8" "#268bd2" "#a00559" "#d33682" "#007d76" "#2aa198" "#839496" "#657b83"))
 '(xterm-color-names
   ["#073642" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#eee8d5"])
 '(xterm-color-names-bright
   ["#002b36" "#cb4b16" "#586e75" "#657b83" "#839496" "#6c71c4" "#93a1a1" "#fdf6e3"])
 '(ycmd-extra-conf-handler 'load))
;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(bm-fringe-persistent-face ((t (:background "dark orange" :foreground "black"))))
 '(bm-persistent-face ((t (:background "dark orange" :foreground "black"))))
 '(snails-content-buffer-face ((t (:background "#111" :height 130))))
 '(snails-header-line-face ((t (:inherit font-lock-function-name-face :underline t :height 1.2))))
 '(snails-input-buffer-face ((t (:background "#222" :foreground "gold" :height 130)))))
